# build

steps:
# init
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-init:latest'
  - '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-init:$SHORT_SHA'
  - '-f'
  - 'Dockerfile.init'
  - '.'

# download
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-download:latest'
  - '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-download:$SHORT_SHA'
  - '-f'
  - 'Dockerfile.download'
  - '.'

# build
- name: 'gcr.io/$PROJECT_ID/idwpan/openwrt-download:latest'
  args:
  - 'make'
  - 'defconfig'
  - '&&'
  - 'make'
  - '-j32'
  - '-O'

timeout: 1800s

images:
- 'gcr.io/$PROJECT_ID/idwpan/openwrt-download:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/idwpan/openwrt-download:latest'
- 'gcr.io/$PROJECT_ID/idwpan/openwrt-init:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/idwpan/openwrt-init:latest'

options:
  machineType: 'N1_HIGHCPU_32'


