# build

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-init:latest',
      '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-init:$SHORT_SHA',
      '-f',
      'Dockerfile.init',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-download:latest',
      '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-download:$SHORT_SHA',
      '-f',
      'Dockerfile.download',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-build:latest',
      '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-build:$SHORT_SHA',
      '-f',
      'Dockerfile.build',
      '.'
    ]

timeout: 7200s

images:
  [
		'gcr.io/$PROJECT_ID/idwpan/openwrt-download:$SHORT_SHA',
		'gcr.io/$PROJECT_ID/idwpan/openwrt-download:latest',
		'gcr.io/$PROJECT_ID/idwpan/openwrt-init:$SHORT_SHA',
		'gcr.io/$PROJECT_ID/idwpan/openwrt-init:latest',
		'gcr.io/$PROJECT_ID/idwpan/openwrt-build:$SHORT_SHA',
		'gcr.io/$PROJECT_ID/idwpan/openwrt-build:latest'
  ]

options:
  machineType: 'N1_HIGHCPU_32'


