# init

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-init:latest', '--tag=gcr.io/$PROJECT_ID/idwpan/openwrt-init:$SHORT_SHA', '-f', 'Dockerfile.init', '.']

timeout: 7200s

images: ['gcr.io/$PROJECT_ID/idwpan/openwrt-init:$SHORT_SHA', 'gcr.io/$PROJECT_ID/idwpan/openwrt-init:latest',]
