FROM debian:buster

RUN apt-get update
RUN apt-get install -y sudo time git-core subversion build-essential \
    g++ bash make libssl-dev patch libncurses5-dev zlib1g-dev gawk \
    flex gettext wget unzip python xz-utils git libssl-dev gettext \
    swig tree rsync nfs-kernel-server
RUN apt-get clean

RUN useradd -m builder && \
    usermod -aG sudo builder  && \
    mkdir /workspace && \
    chown -R builder:builder /workspace

USER builder
